{% set version = "0.2.0" %}

package:
  name: heyoka
  version: {{ version }}

source:
  url: https://github.com/bluescarni/heyoka/archive/v{{ version }}.tar.gz
  sha256: 2ceb718e64bb568fd3765b0b14c028b5430c65708efb491315e66d5cf1c6727c

build:
  number: 0
  run_exports:
    # SO name changes at minor rev bumps.
    - {{ pin_subpackage('heyoka', max_pin='x.x') }}
  skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - clang      # [win]
    - ninja      # [win]

  host:
    - llvmdev
    - llvm
    - boost-cpp
    - fmt
    - sleef
    - xtensor
    - xtensor-blas
    - blas
    - blas-devel
    - mppp  # [linux]

  run:
    - {{ pin_compatible('boost-cpp', max_pin='x.x') }}

test:
  commands:
    - test -f $PREFIX/include/heyoka/heyoka.hpp               # [unix]
    - if not exist %PREFIX%\\Library\\include\\heyoka\\heyoka.hpp exit 1   # [win]

about:
  home: https://bluescarni.github.io/heyoka/
  license: MPL-2.0
  license_file: COPYING
  summary: A C++ library for ODE integration via Taylor's method, based on LLVM

extra:
  recipe-maintainers:
    - bluescarni
